packages:
  - apps/*
  - packages/*

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64

onlyBuiltDependencies:
  - electron-winstaller
  - esbuild
  - msw
  - sharp

allowBuilds:
  electron-winstaller: true
  esbuild: true
  msw: true
  sharp: true
